# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_QR_SCAN
obj-$(CONFIG_OPLUS_FEATURE_QR_SCAN) += oplus_qr_scan/
#endif /* OPLUS_FEATURE_QR_SCAN */
