# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) += oplus_project/
obj-$(CONFIG_OPLUS_FEATURE_RECORD_MDMRST) += mdmrst/

ifdef CONFIG_OPLUS_SYSTEM_KERNEL_QCOM
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)	+= project_info/
endif
